# Generated by Django 3.2.12 on 2022-08-23 00:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import webapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('account_id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='アカウントID')),
                ('username', models.CharField(blank=True, max_length=50, verbose_name='氏名')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'Account',
            },
            managers=[
                ('objects', webapp.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjects', models.CharField(max_length=255, unique=True, verbose_name='科目')),
            ],
            options={
                'db_table': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transportation', models.CharField(max_length=255, unique=True, verbose_name='交通機関')),
            ],
            options={
                'db_table': 'Transportation',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_point', models.CharField(max_length=255, verbose_name='出発地点')),
                ('arrival_point', models.CharField(max_length=255, verbose_name='到着地点')),
                ('fare', models.IntegerField(default=0, verbose_name='金額')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='アカウントID')),
                ('transportation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.transportation', to_field='transportation', verbose_name='交通手段')),
            ],
            options={
                'db_table': 'Route',
            },
        ),
        migrations.CreateModel(
            name='ExpenseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(verbose_name='日付')),
                ('partner', models.CharField(max_length=255, verbose_name='相手')),
                ('purpose', models.CharField(max_length=255, verbose_name='目的')),
                ('lap', models.IntegerField(choices=[[1, '片道'], [2, '往復']], verbose_name='往復')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='アカウントID')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.route', verbose_name='経路')),
                ('subjects', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.subjects', to_field='subjects', verbose_name='科目')),
            ],
            options={
                'db_table': 'Report',
            },
        ),
    ]
